name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github
          chmod 600 ~/.ssh/id_rsa_github
          ssh-keyscan -H 3.111.213.126 >> ~/.ssh/known_hosts

      - name: Sync files to AWS Lightsail (Clean Deployment)
        run: |
          rsync -avz --delete --exclude=".git*" -e "ssh -i ~/.ssh/id_rsa_github -o StrictHostKeyChecking=no" ./ bitnami@3.111.213.126:/opt/bitnami/apache/htdocs/git-test/
