name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.111.213.126 >> ~/.ssh/known_hosts

      - name: Deploy to AWS Lightsail
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no bitnami@3.111.213.126 << 'EOF'
            cd /opt/bitnami/apache/htdocs/git-test
            git pull origin main
          EOF
